---
apiVersion: v1
kind: Pod
metadata:
  name: mytomcattest
  labels:
    env: test
    app: tomcat
    ver: "8"
spec:
  containers:
    - image: tomcat:8
      name: tomcat
      ports:
        - containerPort: 8080
          protocol: TCP
